// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class Atbilde
{
    public int AtbildeID { get; set; }

    public int ProblemaID { get; set; }

    public int JautajumsID { get; set; }

    public string Saturs { get; set; }

    public virtual Jautajums Jautajums { get; set; }

    public virtual Problema Problema { get; set; }

    public virtual ICollection<Lietotajs> Lietotajs { get; set; } = new List<Lietotajs>();
}