// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class Dialogs
{
    public int DialogsID { get; set; }

    public int LietotajsID { get; set; }

    public int SpecialistsID { get; set; }

    public virtual Lietotajs Lietotajs { get; set; }

    public virtual Lietotajs Specialists { get; set; }

    public virtual ICollection<Zina> Zina { get; set; } = new List<Zina>();
}