// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class Jautajums
{
    public int JautajumsID { get; set; }

    public int TestsID { get; set; }

    public string Saturs { get; set; }

    public virtual ICollection<Atbilde> Atbilde { get; set; } = new List<Atbilde>();

    public virtual Tests Tests { get; set; }
}