// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class LietotajsRakstsVertejums
{
    public int LietotajsID { get; set; }

    public int RakstsID { get; set; }

    public byte Balles { get; set; }

    public virtual Lietotajs Lietotajs { get; set; }

    public virtual Raksts Raksts { get; set; }
}