// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class Problema
{
    public int ProblemaID { get; set; }

    public int NozareID { get; set; }

    public string Apraksts { get; set; }

    public virtual ICollection<Atbilde> Atbilde { get; set; } = new List<Atbilde>();

    public virtual Nozare Nozare { get; set; }
}