// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class SajutuNovertejums
{
    public int IerakstsID { get; set; }

    public int LietotajsID { get; set; }

    public DateTime DatumsUnLaiks { get; set; }

    public byte SajutuNovertejums1 { get; set; }

    public string Saturs { get; set; }

    public virtual Lietotajs Lietotajs { get; set; }
}