// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class Tests
{
    public int TestsID { get; set; }

    public int AutorsID { get; set; }

    public string Apraksts { get; set; }

    public virtual Lietotajs Autors { get; set; }

    public virtual ICollection<Jautajums> Jautajums { get; set; } = new List<Jautajums>();
}