// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Models;

public partial class Zina
{
    public int ZinaID { get; set; }

    public int DialogsID { get; set; }

    public int AutorsID { get; set; }

    public DateTime DatumsUnLaiks { get; set; }

    public string Saturs { get; set; }

    public virtual Lietotajs Autors { get; set; }

    public virtual Dialogs Dialogs { get; set; }
}