// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Domain;

public partial class LietotajsSpecialistsVertejums
{
    public int LietotajsID { get; set; }

    public int SpecialistsID { get; set; }

    public byte Balles { get; set; }

    public virtual Lietotajs Lietotajs { get; set; }

    public virtual Lietotajs Specialists { get; set; }
}