// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Domain;

public partial class LietotajsRakstsKomentars
{
    public int LietotajsID { get; set; }

    public int RakstsID { get; set; }

    public DateTime DatumsUnLaiks { get; set; }

    public string Saturs { get; set; }

    public virtual Lietotajs Lietotajs { get; set; }

    public virtual Raksts Raksts { get; set; }
}