// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Domain;

public partial class Loma
{
    public string LomaNosaukums { get; set; }

    public string Apraksts { get; set; }

    public virtual ICollection<LietotajsLoma> LietotajsLoma { get; set; } = new List<LietotajsLoma>();
}