// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalaisGidsAPI.Domain;

public partial class Nozare
{
    public int NozareID { get; set; }

    public string Nosaukums { get; set; }

    public virtual ICollection<Problema> Problema { get; set; } = new List<Problema>();

    public virtual ICollection<Lietotajs> Specialists { get; set; } = new List<Lietotajs>();
}